### ISSUE TITLE
Watcher - No output information as expected

### ISSUE THREAD

**Issue by M3lk4rt** [gregghz/Watcher#17]
Hi all,

I'm trying to get working your watcher's script on my xubuntu. I've moved the file watcher.py to /bin/watcher as root so these are its properties:

1574797 -rwxr-xr-x 1 root root 14469 feb  5 21:55 watcher.py

I run the script with my local user (david) and it creates the pid file on ~/.watcher:

1970263 -rw-rw-r--  1 david david   99 feb  5 22:08 watcher.log
1970265 -rw-rw-rw-  1 david david 4525 feb  5 22:03 jobs.yml
1970264 -rw-rw-rw-  1 david david    6 feb  5 22:03 watcher.pid

jobs.yml is the current example file that you uploaded to github. I've also checked that the daemon is running fine. This is the ps -aux | grep watcher output:

david    20901  0.0  0.2 133984 10628 ?        Sl   22:03   0:00 python ./watcher.py start
david    21180  0.0  0.0  18952   916 pts/0    S+   22:24   0:00 grep --color=auto watcher

I made some tests in /var/www and checked watcher.log:

2015-02-05 22:08:22 /var/www/test.lala IN_DELETE
2015-02-05 22:08:41 /var/www/piopio.txt IN_CREATE

The script seems to be watching all the changes however I can't see the echo output defined:

command: echo $datetime $filename $tflags # $src_path

I don't see anything echoed. I've also tried to run the script as root but I can't see any information on the screen. However, watcher.log is logging the events

Am I doing something wrong?
Thank you in advance!

**Comment by gregghz** [comment]
I don't believe output from commands is redirected. Instead of just
echoing, try redirecting the output of your command to a file:

command: echo $datetime $filename $tflags >> /tmp/output

then you can tail /tmp/output:

tail -f /tmp/output

and you should then (hopefully) see everything happening as you expect.

**Comment by M3lk4rt** [comment]
Hi gregghz, I tested that "command:" sentence but no file was created.

I also tried echo "test" >> /tmp/output in a terminal in order to test if my user has permission problems but the file was created fine.

I don't know what is going on, but the "command:" sentence seems to be failing in my system
Note: I'm running the script as my user (not root)

**Comment by gregghz** [comment]
try python ./watcher.py debug

That will make it so it doesn't daemonize and you should be better able to
debug what's going on. There are probably still bugs with output and
logging when it's daemonized.

**Comment by M3lk4rt** [comment]
This is what I see when I'm debugging

david@david-Studio-1558:/$ /bin/watcher/watcher.py debug
2015-02-06 00:22:08.155350
<open file '/home/david/.watcher/jobs.yml', mode 'r' at 0x7f66bada9ae0>
job1

Creating:  /var/www/html/aksa
2015-02-06 00:22:49 /var/www/html/aksa IN_CREATE >> /home/david/output

but no file is created in /home/david/output. The trigger works fine, but the command is not being executed :(

**Comment by M3lk4rt** [comment]
Hi gregghz,

Never mind, I've changed the "command:" to:
command: chown www-data:www-data $filename

That was my main purpose and it works fine (as root of course). 
Thank you very much! great script dude!
