### ISSUE TITLE
ModuleNotFoundError: No module named 'pyinotify'

### ISSUE THREAD

**Issue by mukeshkdangi** [gregghz/Watcher#22]
I'm always getting this error on Mac OS and Py3. 
Can you please me out to rectify this ? i did my reasech but no luck 
```
Traceback (most recent call last):
  File "watcher.py", line 24, in <module>
    import pyinotify
ModuleNotFoundError: No module named 'pyinotify'
```

**Comment by gregghz** [comment]
pyinotify is a linux-only module. It depends on the inotify subsystem.

Try [fswatch](https://github.com/emcrisostomo/fswatch) for a cross platform solution.
